#this workflow will run automatically run on any pull request, or can be manually triggered
name: PR - Build / Test
on:
  pull_request: #run on pull request
    branches: #to specific branch
      - main #trigger on pull request to main branch
  workflow_dispatch:
jobs:
  build: #name of job
    runs-on: ubuntu-latest
    steps:
      #checkout git branch
      - name: checkout code
        uses: actions/checkout@v4 #from marketplace, we use the tag v4 of the checkout action
      #setup dotnet
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: "8.0.x" #specify the dotnet version to be used
      #run dotnet restore
      - name: Restore dependencies
        run: dotnet restore "${{ github.workspace }}/src/my-web-app.sln"
      #build dotnet
      - name: Build
        run: dotnet build "${{ github.workspace }}/src/my-web-app.sln" --no-restore --configuration
      #Testing
      - name: Testing
        run: dotnet test "${{ github.workflow }}/src/my-web-app.sln" --no-restore --logger:"junit;LogFilePath=${{ github.workspace }}/results/test-results.xml"
      # create a test summary markdown file
      # failure to specify output file, it will automatically add as a job summary
      # if we specify an output file, we have to create our own step of adding it to the job summary
      - name: Create test summary
        uses: test-summary/action@v2.4 #we use the test-summary action to take in the test result file, and turn it into a markup file with it cleaner and more organized 
        with:
          paths: ${{ github.workspace }}/results/*.xml
          output: ${{ github.workspace }}/results/summary.md
          show: "all"
        if: always()

      # Add test results to summary job
      - name: Add test Results to Job summary
        run: |
          echo "TEST RESULTS: " >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # blank line
          cat "${{ github.workspace }}/results/summary.md" >> $GITHUB_STEP_SUMMARY
        if: always()

      - name: Publish
        run: dotnet publish "${{ github.workspace }}/src/my-web-app/my-web-app.csproj" -c Release -o mywebapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: mywebapp/**
          if-no-files-found: error
        






      
